[package]
name = "dust"
version = "0.1.0"
edition = "2024"

[dependencies]
dust-sys.workspace = true

miette = { version = "7.6", features = ["fancy"] }
clap = { version = "4.5", features = ["derive"] }
